/**
 * CiviNest Priority Engine (Deterministic)
 *
 * The priority score is NEVER generated by AI or random.
 * It is computed from configured weights applied to structured signals.
 *
 * Priority Score (0–100) =
 *   SeverityWeight
 * + PublicSafetyWeight
 * + UrgencyWeight
 * + ServiceCriticalityWeight
 * + ClusterWeight
 * + EvidenceConfidenceWeight
 *
 * Safety overrides guarantee critical safety issues never score below a
 * configured floor. Low AI confidence caps the achievable score.
 */

export interface PriorityInput {
  severity: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' | 'UNKNOWN';
  urgency: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' | 'UNKNOWN';
  aiConfidence: number | null; // 0–1 or null when unavailable
  publicSafety: boolean;
  affectedService: string;
  clusterSize?: number;
  evidenceQuality?: number; // 0–1
  recurrence?: number; // 0–1
}

export interface PriorityFactor {
  name: string;
  contribution: number;
}

export interface PriorityResult {
  score: number;
  level: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  factors: PriorityFactor[];
  calculatedAt: Date;
  engineVersion: string;
  safetyOverride?: boolean;
}

export const PRIORITY_ENGINE_VERSION = '1.0';

// ── Configurable weights (single source of truth) ──

export const PRIORITY_CONFIG = {
  weights: {
    severity: 30,
    publicSafety: 20,
    urgency: 15,
    serviceCriticality: 15,
    cluster: 10,
    evidenceConfidence: 10,
  },
  severityScores: { LOW: 15, MEDIUM: 40, HIGH: 70, CRITICAL: 95, UNKNOWN: 20 } as const,
  urgencyScores: { LOW: 10, MEDIUM: 35, HIGH: 65, CRITICAL: 90, UNKNOWN: 20 } as const,
  serviceCriticality: {
    water: 90,
    electricity: 85,
    safety: 100,
    sanitation: 60,
    roads: 50,
    environment: 30,
    unknown: 25,
  },
  safetyFloor: 70, // Critical public safety never scores below this
  confidenceCap: 0.9, // Low confidence caps max achievable score
  minConfidenceForHighPriority: 0.35,
} as const;

const SEVERITY_LEVEL: Record<number, 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'> = {
  0: 'LOW',
};

function severityRank(s: PriorityInput['severity']): number {
  return { LOW: 0, MEDIUM: 1, HIGH: 2, CRITICAL: 3, UNKNOWN: 0 }[s];
}

function computeLevel(score: number): 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL' {
  if (score >= 80) return 'CRITICAL';
  if (score >= 60) return 'HIGH';
  if (score >= 35) return 'MEDIUM';
  return 'LOW';
}

export function calculatePriority(input: PriorityInput): PriorityResult {
  const { weights } = PRIORITY_CONFIG;
  const factors: PriorityFactor[] = [];

  // 1. Severity (weighted, scaled to weight max)
  const severityScore = PRIORITY_CONFIG.severityScores[input.severity] ?? 20;
  const severityContribution = (severityScore / 100) * weights.severity;
  factors.push({ name: 'Severity', contribution: Math.round(severityContribution) });

  // 2. Public safety (binary gate with high weight)
  const safetyContribution = input.publicSafety ? weights.publicSafety : weights.publicSafety * 0.2;
  factors.push({ name: 'Public Safety', contribution: Math.round(safetyContribution) });

  // 3. Urgency
  const urgencyScore = PRIORITY_CONFIG.urgencyScores[input.urgency] ?? 20;
  const urgencyContribution = (urgencyScore / 100) * weights.urgency;
  factors.push({ name: 'Urgency', contribution: Math.round(urgencyContribution) });

  // 4. Service criticality
  const critMap = PRIORITY_CONFIG.serviceCriticality as Record<string, number>;
  const crit = critMap[input.affectedService] ?? 25;
  const serviceContribution = (crit / 100) * weights.serviceCriticality;
  factors.push({ name: 'Service Criticality', contribution: Math.round(serviceContribution) });

  // 5. Cluster size (more reports → higher contribution)
  const clusterSize = input.clusterSize ?? 1;
  const clusterScale = Math.min(clusterSize / 10, 1);
  const clusterContribution = weights.cluster * clusterScale;
  factors.push({ name: 'Cluster Size', contribution: Math.round(clusterContribution) });

  // 6. Evidence confidence
  const evidence = input.evidenceQuality ?? 0.5;
  const evidenceContribution = weights.evidenceConfidence * evidence;
  factors.push({ name: 'Evidence Confidence', contribution: Math.round(evidenceContribution) });

  let score = Math.round(
    severityContribution +
      safetyContribution +
      urgencyContribution +
      serviceContribution +
      clusterContribution +
      evidenceContribution
  );

  let safetyOverride = false;

  // ── Deterministic safeguards ──

  // Safety floor: critical public safety never below threshold
  if (input.publicSafety && input.severity === 'CRITICAL' && score < PRIORITY_CONFIG.safetyFloor) {
    score = PRIORITY_CONFIG.safetyFloor;
    safetyOverride = true;
  }

  // Confidence cap: uncertain classifications can't produce unjustifiably high priority
  if (input.aiConfidence !== null && input.aiConfidence < PRIORITY_CONFIG.minConfidenceForHighPriority) {
    score = Math.min(score, Math.round(100 * (input.aiConfidence / 0.35)));
  }

  // Clamp
  score = Math.min(Math.max(score, 0), 100);

  return {
    score,
    level: computeLevel(score),
    factors,
    calculatedAt: new Date(),
    engineVersion: PRIORITY_ENGINE_VERSION,
    safetyOverride,
  };
}
